# Site settings
title: The musings of Jamil Lawrence
email: jamil.lawrence@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  I blog about things that topics that make me curious.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://yourdomain.com" # the base hostname & protocol for your site
twitter_username: TheJDLawrence
github_username:  jdlawrence

# Build settings
markdown: kramdown
